#!/bin/bash
# co2do.sh
# by hackerb9, February 2026
#
# Given a .CO machine language file for a TRS-80 Model 100 (or
# similar), creates a .DO file containing a two-stage BASIC loader
# which will install the .CO to the correct address and start it.

# This program uses a small assembly routine to decode and write the
# bytes to memory, which is a hundred times faster than doing it in
# BASIC. See decode.asm and the dodo() function.
#
# USAGE: co2do.sh FOO.CO FOO.DO
#        Transfer FOO.DO to M100.
#        On M100: run "FOO"
#
# Features:
#
# * BASIC loader writes .CO to memory very quickly (less than a second).
#
# * Inspired by Stephen Adolph's efficient encoding scheme which
#   increases storage size by at most 2x + k (where k is approx. 500),
#   and on average closer to 1.3x + k.
#
# * Works on all of the Kyotronic Sisters:
#     Kyocera Kyotronic 85, TRS-80 Model 100/102, Tandy 200, Olivetti M10,
#     NEC PC-8201/8201A/8300.
#
# * BASIC Automatically CLEARs the correct space and CALLs the program.
#
# * Uses .CO header to detect where to POKE, length mismatch, and CALL addr.
#
# * As a special bonus, if you use the -t option, it will display a
#   Unicode version of the program instead of writing to a .DO file.
#   (Requires the tandy-200.charmap file from hackerb9/tandy-locale.)

# Todo:
#       * Prevent writing to bad parts of RAM.
#         (E.g., POKE Q where Q<HIMEM or Q>=MAXRAM).
#

set +o errexit
set +o pipefail

function usage() {
    cat <<EOF
Usage: co2do.sh <INPUT.CO> [OUTPUT.DO]
EOF
}

function main() {
    declare -i TOP LEN EXE
    declare -i ROT=136		# Rotate character set for efficiency
    TOP=$1+$2*256
    LEN=$3+$4*256
    EXE=$5+$6*256
    shift 6
    if [[ ! $quiet ]]; then
	cat<<-EOF >&2
		TOP: $TOP
		END: $((TOP+LEN))
		EXE: $EXE
		ROT: $ROT
	EOF
    fi
    if [[ $# -ne $LEN ]]; then
	echo "Warning filesize mismatch! $# bytes found after header, not $LEN." >&2
	if [[ $# -gt $LEN ]]; then
	    echo "Truncating output to $LEN bytes." >&2
	    set -- "${@:1:LEN}"
	fi
    fi
    if (( TOP<62960 && TOP>32767 )); then clear=", $TOP"; else clear=""; fi
    cat <<-EOF
	10 MAXFILES=0: CLEAR 256$clear: NM$="${coname}"
	20 TP=$((TOP)): LN=$LEN: EX=$((EXE)): RT=$((ROT)): ID=PEEK(1)
	40 GOSUB 12000: GOSUB 13000
	50 IF FRE(0) < LN THEN ?"Insufficient space to save "NM$: Q$=CHR\$(34): C$=",":?"Please try NEW then SAVEM "Q$;NM$;Q$;C$;TP;C$;TP+LN;C$;EX: END
	60 IF ID<>148 THEN SAVEM NM$,TP,TP+LN,EX ELSE BSAVE NM$,TP,TP+LN,EX
	80 IF ID<>148 THEN CALL EX ELSE EXEC EX
	90 END
	EOF
    emitmldecode
    emitbasicdecode
    printf "14000 '${coname}"
    emitdata "$@"
    emitnecvarptr
    true			# XXX todo: call external warnmem util
    return			# Return result from warnmem
}

function emitdata() {
    local -i linenum=14000
    local -i v
    for v; do
	v=(v+$ROT)%256
	if (( count++ % 120 == 0 )); then
	    printf '\n%d DATA"' $((linenum+=10))
	fi
	# Escape Quote (34), Bang (33), DEL (127), and ctrl chars (except Tab)
	if (( (v<35 && v!=9 && v!=32) || v==127 )); then
	    v=v+128
	    printf "!"
	fi
	printf -v x "%x" $v
	printf "\x$x"
    done
    # End of DATA marked by '!!'
    printf '\n%d DATA !!\n' $((linenum+=10))
}

function emitmldecode() {
    # BASIC wrapper for the M/L routine to decode DATA strings fast.
    # Sets the BASIC variable DX to the address of the routine.
    # NB: the machine language is stored in a BASIC string and called
    # directly, so any further string manipulations in BASIC can foul
    # it up. (READ is okay.)
    cat <<-EOF
	12000 'Fast loader
	12010 DC$=SPACE\$(255): IF PEEK(1)<>148 THEN DC=VARPTR(DC$): ELSE VY$="DC$": GOSUB 40000: DC=L+256*H
	12015 DX=PEEK(DC+1)+256*PEEK(DC+2): Q=DX
	12020 READ X
	12030 IF X=-1 THEN 12080
	12040 IF X=-7 THEN READ L: READ H: A=H*256+L+DX: X=INT(A/256): L=A-X*256: POKE Q, L: Q=Q+1
	12050 POKE Q, X
	12060 Q=Q+1
	12070 GOTO 12020
	12080 POKE DC, Q-DX: 'Set length of DC$
	12090 RETURN
	EOF
    dodo
}

function emitbasicdecode() {
    # Calls M/L routine to decode and install each DATA string.
    # DX is the start address of decode.asm, set by emitmlcode().
    # TP is the destination address ("TOP"), set by main().
    cat <<-"EOF"
	13000 REM ?"Loading "NM$" ("LN" bytes) at "TP
	13010 RESTORE 13000
	13020 IF PEEK(1)<>148 THEN CALL DX, RT, TP: ELSE H=(TP)/256: L=TP-H*256: POKE 63912, L: POKE 63913, H: EXEC DX
	13030 READP$: IF P$="!!" GOTO 13080
	13040 IF PEEK(1)<>148 THEN P=VARPTR(P$): CALL DX+9, 0, P: ELSE VY$="P$": GOSUB 40000: POKE 63912, L: POKE 63913, H: EXEC DX+9
	13060 GOTO 13030
	13080 'All done
	13090 ?:RETURN
	EOF
}

emitnecvarptr() {
    # VARPTR by Gary Weber of web8201.net
    # Entry: VY$ must contain the name of variable of interest
    # Exit: H & L contain variable's address, TY contains type
    # Example:
    #   100 A$="This is a sample string."
    #   110 VY$="A$":GOSUB 40000
    #   120 PRINT "VARPTR of ";VY$;" is ";L+(H*256)
    cat <<-EOF
	39999 'VARPTR by Gary Weber for NEC 8201/8300
	40000 H=0:L=0:TY=0
	40010 POKE64448,205:POKE64449,175:POKE64450,73:POKE64451,235
	40020 POKE64452,58:POKE64453,139:POKE64454,250:POKE64456,201
	40030 IFVY$=""THENPRINT"VY$ not defined!":STOP
	40040 FORH=1TO7:POKEH+64456,ASC(MID\$(VY$,H,1)+CHR\$(0)):NEXT:POKE64464,0
	40050 POKE63912,201:POKE63913,251:EXEC64448
	40060 L=PEEK(63912!):H=PEEK(63913!):TY=PEEK(63911!)
	40070 RETURN
	EOF
}


# XXX todo: update this from decode.asm.lst automatically.
DECODEASMLST=$(cat <<EOF
                        	;; Given a destination address and the varptr of a BASIC
                        	;; string, copy the source string to the destination,
                        	;; processing !-escapes by replacing each '!' with the
                        	;; subsequent character with the high-bit flipped.

                        	;; Calling is a two step process. First, the destination
                        	;; address is sent from BASIC in HL by calling DCINIT.
                        	;; Second, MAIN (= DCINIT+6) is called with the varptr of
                        	;; the source string in HL.

                        	;; The call to DCINIT also specifies a number in register A
                        	;; from 0 to 255 to be subtracted from every byte. This allows
                        	;; the coding to be more efficient by rotating the character
                        	;; set.

                        	;; Upon return, the length of the source string is modified to
                        	;; reflect the actual number of characters written to the
                        	;; destination address. The source string data is NOT changed.

                        	;; Example usage from BASIC:
                        	;;      10 DC=(DCINIT address after relocation)
                        	;; 	15 A=(rotation offset or 0)
                        	;;      20 Q=(destination buffer address)
                        	;; 	30 READ P$: IF P$="EOD" THEN END
                        	;;  	40 CALL DC, A, Q
                        	;; 	50 CALL DC+6, 0, VARPTR(P$)
                        	;; 	60 Q=Q+LEN(P$)
                        	;; 	70 GOTO 30
                        	;;
                        	;; When appending multiple strings to the same buffer, the
                        	;; destination address does not need to be updated each time.
                        	;; The following is equivalent to the above code:

                        	;;      10 DC=(DCINIT address after relocation)
                        	;; 	15 A=(rotation offset or 0)
                        	;;  	20 CALL DC, A, (destination buffer address)
                        	;; 	30 READ P$: IF P$="EOD" THEN END
                        	;; 	40 CALL DC+6, 0, VARPTR(P$)
                        	;; 	50 GOTO 30

0000                    	CPU 8085		; Build with asmx -w -e -l -b0 decode.asm

0000                    	ORG 0			; The BASIC loader relocates this routine.
0000                    DCINIT:	
0000  32 2A00           	STA ROT			; Save A as Rotation Offset for charset
0003  22 0700           	SHLD DEST		; Save HL in DEST as destination address.
0006  C9                	RET

0007  0000              DEST:	DW 0

0009                    MAIN:	
                        	;; HL starts as VARPTR(P$) where P$ is bang-encoded.
0009  E5                	PUSH H
000A  46                	MOV B, M		; B is length of input string
000B  0E 00             	MVI C, 0		; C will be resulting length
000D  23                	INX H
000E  5E                	MOV E, M		; Load actual address of string into DE
000F  23                	INX H
0010  56                	MOV D, M
0011  2A 0700           	LHLD DEST		; Restore HL from saved DEST
0014  EB                	XCHG			; Now HL is P$'s actual address
                        				; and DE is address of destination
0015  78                	MOV A, B
0016  A7                	ANA A
0017  CA 3400           	JZ END			; Zero-length string?
001A                    LOOP:	
001A  7E                	MOV A, M		; Get next byte from source (*HL)
001B  FE 21             	CPI '!'
001D  C2 2800           	JNZ WRITE		; If not '!' just copy the character.
0020  05                	DCR B
0021  CA 3400           	JZ END			; Ignore escape char with no following char.
0024  23                	INX H			; Char is '!' so get next char in A
0025  7E                	MOV A, M
0026  EE 80             	XRI 128			; Decode character by flipping bit 7
0028                    WRITE:	
0028  EB                	XCHG
0029  D6                	DB D6h			; D6 is SUI instruction.
002A  00                ROT:	DB 0			; Subtract this value from char.
002B  77                	MOV M, A		; Copy the byte from *HL to *DE.
002C  EB                	XCHG
002D  23                	INX H
002E  13                	INX D
002F  0C                	INR C
0030  05                	DCR B
0031  C2 1A00           	JNZ LOOP
0034                    END:	
0034  EB                	XCHG			; Save DE in DEST so next call can skip DCINIT
0035  22 0700           	SHLD DEST
0038  EB                	XCHG			; Not needed, just being overly fastidious
0039  E1                	POP H
003A  71                	MOV M, C		; Write new length to BASIC string
                        	
003B  C9                	RET

00000 Total Error(s)

DCINIT             00000000    DEST               00000007    END                00000034
LOOP               0000001A    MAIN               00000009    ROT                0000002A
WRITE              00000028
EOF
)

function dodo() {
    # dodo: DATA output decode.asm to .DO.
    # Given the filename of an assembly listing (from `asmx -l`), output
    # the bytes as decimal values separated by commas in a DATA statement.
    # Addresses that will need to be relocated are prefixed with -7.
    # End of data is signaled by -1.

    # Use the cached copy in $DECODEASMLST, unless the file
    # "decode.asm.lst" exists in the current directory,
    if [[ -r "decode.asm.lst" ]]; then
	DECODEASMLST=$(cat "decode.asm.lst")
    fi
    echo -n "12500 DATA "
    echo "$DECODEASMLST" | parselst
    echo -1
    return
}

function parselst() {
    # Parse an assembly listing on stdin and output data values.
    # Whenever an address is seen, prefix it with -7.
    # This routine is fragile, but it only needs to work with one
    # program: decode.asm (which see). Also see, dodo().
    sed -rn '/^[0-9A-Fa-f]{4} /p' | cut -c 6-19 |
	while read op arg; do
	    case ${#op} in
		0) continue ;;
		2) echo "ibase=16; $op" | bc ;;
		4) # Data for DW looks like a 16-bit opcode.
		    echo "ibase=16; ${op:0:2}" | bc
		    echo "ibase=16; ${op:2:2}" | bc
		    ;;
		*)
		    echo "parselst error: What is op in '$op $arg'?" >&2
	    esac
	    case ${#arg} in
		0) continue ;;
		2) echo "ibase=16; $arg" | bc ;;
		4) # Escape address for relocation with -7
		    echo -7
		    echo "ibase=16; ${arg:0:2}" | bc
		    echo "ibase=16; ${arg:2:2}" | bc
		    ;;
		*)
		    echo "parselst error: What is arg in '$op $arg'?" >&2
	    esac
	done | tr -s '\n' ','
}


{    # CLI args
    tandycharset=cat
    quiet=""
    while getopts 'qt' name; do
	case $name in
	    q) quiet=: ;;
	    t) tandycharset="iconv -f $(dirname $0)/tandy-200.charmap"  ;;
	    *) exit 1 ;;
	esac
    done
    shift $(($OPTIND - 1))

    if [ -z "$1" ]; then usage; exit 1; fi
    if [[ "$1" == "-" ]]; then shift; set -- /dev/stdin "$@"; fi
    if [ ! -r "$1" ]; then
	echo "'$1' is not readable"
	exit 1
    else
	input="$1"
    fi

    output=/dev/stdout
    if [ "$2" ]; then
	output="$2"
	shift
    elif [[ $tandycharset == "cat" ]]; then
	if [[ $input == *.CO ]]; then
	    output=${input%.CO}.DO
	elif [[ $input == *.co ]]; then
	    output=${input%.co}.do
	fi
    fi
    coname=$(basename "$output")
    coname=${coname%%.*}
    coname=${coname:0:6}
    coname=${coname@U}.CO
}

outputfilter() {
    # Add carriage returns since NEC PC-8201 uses Mac (or DOS?) line endings.
    # Append ^Z at end of file to signal M100 that file is finished.
    sed 's/$/\r/g'
    printf '\x1A'
}

main $(od -t u1 -v -An "$input") | $tandycharset | outputfilter > "$output"
err=${PIPESTATUS[0]}
if (( err != 0 )); then
    echo "Exiting with error $err" >&2
    exit $err
fi

if [[ $tandycharset == "cat" && -z $quiet ]]; then
    outnodo=${output##*/}
    outnodo=${outnodo%.[Dd][Oo]}
    cat <<-EOF
	Now transfer $output to your Model-T
	and in BASIC type
	    run "${outnodo:0:6}"
	EOF
fi

exit $err
