#!/bin/bash -e
# dodo: Given an assembly listing from `asmx -l`, output the bytes as
# decimal values separated by commas for a DATA statement.
# Addresses that will need to be relocated are prefixed with -7.
# End of data is signaled by -1.

# Unlike co2do, this program is fragile, but it only needs to work for
# one program: decode.asm, which see. (Later this program will be
# folded into co2do proper.)

function usage() {
    cat <<EOF
Usage: dodo <INPUT.ASM.LST>
EOF
}

function main() {
    echo -n "12500 DATA "
    cat "$@" | parselst
    echo -1
    return
}


function parselst() {
    sed -rn '/^[0-9A-Fa-f]{4} /p' | cut -c 6-19 | 
	while read op arg; do
	    case ${#op} in
		0) continue ;;
		2) echo "ibase=16; $op" | bc ;;
		4) # Data for DW
		    echo "ibase=16; ${op:0:2}" | bc
		    echo "ibase=16; ${op:2:2}" | bc
		    ;;
		*)
		    echo "Dodo error: What is op in '$op $arg'?" >&2
	    esac
	    case ${#arg} in
		0) continue ;;
		2) echo "ibase=16; $arg" | bc ;;
		4) # Escape address for relocation with -7
		    echo -7
		    echo "ibase=16; ${arg:0:2}" | bc
		    echo "ibase=16; ${arg:2:2}" | bc
		    ;;
		*)
		    echo "Dodo error: What is arg in '$op $arg'?" >&2
	    esac
	done | tr -s '\n' ','
}

main "$@"
