#!/bin/bash -e
# dodo: Given an assembly listing from `asmx -l`, output the bytes as
# decimal values separated by commas for a DATA statement.
# Addresses that will need to be relocated are prefixed with -7.
# End of data is signaled by -1.

# Unlike co2do, this program is fragile, but it only needs to work for
# one program: decode.asm, which see. (Later this program will be
# folded into co2do proper.)

function usage() {
    cat <<EOF
Usage: dodo <TOPADDR> <INPUT.ASM.LST>
EOF
}

function main() {
    declare -i TOP=$1
    shift

    echo -n "12500 DATA "
    cat "$@" | parselst
    echo -1
    return
}

function disabledemitml() {
    cat <<-EOF
    # Install the M/L routine to decode DATA strings rapidly
    cat <<-EOF
    	12000 'Install tiny M/L program to decode and install the rest
	12005 Q=63574: ST=Q
	12010 READ X
	12020 IF X=-1 THEN 12090
	12030 IF X=-7 THEN READ L: READ H: A=H*256+L+ST-1: H=INT(A/256): L=A-H*256: POKE Q, L: Q=Q+1: POKE Q, H: GOTO 12050
	12040 POKE Q, X
	12050 Q=Q+1
	12060 GOTO 12010 
	12090 RETURN
	EOF
}

function parselst() {
    sed -rn '/^[0-9A-Fa-f]{4} /p' | cut -c 6-19 | 
	while read op arg; do
	    case ${#op} in
		0) continue ;;
		2) echo "ibase=16; $op" | bc ;;
		4) # Data for DW
		    echo "ibase=16; ${op:0:2}" | bc
		    echo "ibase=16; ${op:2:2}" | bc
		    ;;
		*)
		    echo "Dodo error: What is op in '$op $arg'?" >&2
	    esac
	    case ${#arg} in
		0) continue ;;
		2) echo "ibase=16; $arg" | bc ;;
		4) # Escape address for relocation with -7
		    echo -7
		    echo "ibase=16; ${arg:0:2}" | bc
		    echo "ibase=16; ${arg:2:2}" | bc
		    ;;
		*)
		    echo "Dodo error: What is arg in '$op $arg'?" >&2
	    esac
	done | tr -s '\n' ','
}

main "$@"
